---
node: 'kvm1'
api_host: '54.39.129.20'
api_user: 'ansible-provision@pve'
api_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36653936313962613465666137366536626461353165633335656130633266323630346664343265
          3762313662373931646332636362633039393139363833350a323237626334303064393036636135
          31383831333465613233383632363838386131306438353964636465646566386631393961356163
          3264353162633336390a366366633033373636626265633536366237343435393835393436623361
          35633636666638383436656337303064633065316163316464306532353761646461663461363135
          65616134383739666439373864643237313739333934303465653062616530646666643638326562
          65353263653663633066663834326433383231666238633335366436323234363230383232643261
          32326330613332373462
clone: 'cloud-init-debian-10.4.3'
storage: 'local'
vm_id: '1004'
vm_name: 'lists.hypha.coop'
vm_disk: '20G'
vm_ram: '1024'
vm_cores: '4'
vm_cpu: 'host'
vm_cpuunits: '1024'
vm_mac_0: '02:00:00:14:dc:0d'
vm_bridge_0: 'vmbr0'
vm_ip4_0: '198.50.215.3/32'
vm_gw4_0: '54.39.129.254'
vm_ip6_0: '2607:5300:203:4014:4879:7068:614c:5354/56'
vm_gw6_0: '2607:5300:0203:40ff:ff:ff:ff:ff'
vm_username: 'sysadmin'
vm_sshkey_file: '~/.ssh/id_rsa.pub'
nameserver: '213.186.33.99'
search_domain: 'hypha.coop'